version: "3.7"

services:
  jenkins:
    container_name: jenkins_dockerized
    image: jenkins_dockerized
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - ${HOST_DOCKER}:/var/run/docker.sock
      - ./jenkins_home:/var/jenkins_home
